stages:
  stage_01:
    cmd: python stage_01.py
    deps:
      - stage_01.py
    outs:
      - artifacts01.txt

  stage_02:
    cmd: python stage2.py
    deps:
      - stage2.py
      - artifacts01.txt